server:
  port: 3068
  servlet:
    context-path: /admin
    session:
      timeout: 1d
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30

spring:
  application:
    name: also-admin
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,extend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: temp
  messages:
    basename: i18n/messages,i18n/messages-custom
    encoding: UTF-8

#  boot:
#    admin:
#      client:
#        url: http://localhost:4000

management:
  metrics:
    tags:
      application: actuator-demo
  endpoints:
    web:
      exposure:
        include: '*'
#      base-path: /metrics
  endpoint:
    health:
      show-details: always


mybatis-plus:
  type-aliases-package: com.also.admin.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: debug

security:
  basic:
    enabled: true

