border:
  after:
    service:
      #ftp
      ftp:
        hostname: 44.196.151.3
        username: ftpuser01
        password: 666dgJY#&
    #        encrypt: jasypt

also:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password: also
      expireSecond: 10