# datasource config
also:
  datasource:
    allow-page: true
    type: druid
    data-source-configs:
      - name: pg
        defaultDatabase: true
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/dg_ssp
        username: postgres
        password: postgres
      - name: oracle
        defaultDatabase: false
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:also
        username: dg_ssp
        password: dg_ssp123